services:
  - type: web
    name: portfolio-frontend
    env: static
    plan: free
    region: oregon  # or any preferred region
    buildCommand: |
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://portfolio-backend-9ttg.onrender.com
      - key: REACT_APP_ENABLE_VISUAL_EDITS
        value: false
      - key: ENABLE_HEALTH_CHECK
        value: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html